all: main_panel side_panel side_brace

clean:
	rm MainPanel.dxf
	rm SidePanel.dxf
	rm SideBrace.dxf

main_panel:
	openscad MainPanel.scad -o MainPanel.dxf

side_panel:
	openscad SidePanel.scad -o SidePanel.dxf

side_brace:
	openscad SideBrace.scad -o SideBrace.dxf
